# Netlify configuration file

# Build settings
[build]
  publish = "dist"
  command = "npm run build"
  
  # Post-build hooks
  [build.environment]
    POST_BUILD_SCRIPT = "netlify/build-hooks.js"
  
  # Run post-build script
  [build.processing]
    after = ["node ${POST_BUILD_SCRIPT}"]

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add appropriate headers for audio files
[[headers]]
  for = "/sounds/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Content-Type = "audio/mpeg"

# Specify functions configuration - using simple configuration
[functions]
  directory = "netlify/functions"